FROM jenkins/jenkins:2.95-alpine
LABEL org.opencontainers.image.authors="mail@jesstruck.dk"

# To avoid jenkins to run setup wizard
ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"


# Environment setup
COPY conf.groovy /usr/share/jenkins/ref/init.groovy.d/conf.groovy

#Job Seeding
COPY jobs.groovy /usr/share/jenkins/ref/init.groovy.d/jobs.groovy